### PR TITLE
RfC: Migrate to TypeScript

### PR DESCRIPTION
**Pull request by simon04**
I've migrated the code to TypeScript for an easier integration in TypeScript projects. Feel free to apply or reject.

### CODE REVIEW

**Comment by broofa** [comment]
Thanks for the PR.  I'm not ignoring this... rather, there's more involved to converting to TS than simply renaming *.js to *.ts  (As this would break any applications that don't do TS compilation as part of bundling.)  We'll need to build the *.js file as part of `prepare`ing the module for publication.

**Comment by simon04** [comment]
I've successfully integrated the build step in other projects using https://esbuild.github.io/ or https://github.com/developit/microbundle.

**Comment by broofa** [comment]
> using https://esbuild.github.io/

Finally getting around to this. :-)  FWIW, of the two solutions you suggest...
* `microbundle` has a [large dependency graph](https://npmgraph.js.org/?q=microbundle) that I'd rather not pull into this project
*`esbuild` doesn't actually support generation of type declaration files

So... 'just rolling with good 'ol `tsc` for this.  It seems to work well enough.

**Comment by broofa** [comment]
Published as checkcss@1.2.0

**Pull request merged**
